destination: ./_site
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title : 3 IBC

menu :
  - url: /index.html
    title: Home
    tagline: This is 3IBC
  - url: /manuals.html
    title: Manuals
    tagline: Manuals for white goods and other equipment
  - url: /facilities.html
    title: Facilities
    tagline: Local facilities
  - url: /contacts.html
    title: Contacts
    tagline: Contacts and links
